### ISSUE TITLE
상품 수정

### ISSUE THREAD

**Issue by hyee0715** [Team-PalPalHae-Dealight/Team-PalPalHae-Dealight-BE#13]
## 💻 Describe
- 상품 수정 기능을 구현합니다.

## ✅ Tasks
- [ ] 엔티티에 수정 메서드 추가
- [ ] 수정 시 유효성 검사
- [ ] 수정 서비스 로직 구현
- [ ] 수정 api 엔드포인트 연결
- [ ] 수정 테스트 코드, Rest Docs 명세 코드 작성
