### ISSUE TITLE
스프링 액츄에이터, 메트릭, 프로메테우스, 그라파나 도입

### ISSUE THREAD

**Issue by Dev-Yesung** [Team-PalPalHae-Dealight/Team-PalPalHae-Dealight-BE#146]
## 💻 Describe
- 이슈 설명

서버 모니터링 툴인 스프링 액츄에이터, 메트릭, 프로메테우스, 그라파나를 도입해보겠습니다.
이 세 개가 따로 설정해서 돌아가는 것보다는, 함께 설정했을 때
시너지를 발휘 할 수 있는 툴이라 함께 적용하겠습니다.

## ✅ Tasks
- [ ] 스프링 액츄에이터 도입 및 세부 설정
- [ ] 메트릭 설정 + 프로메테우스 도입 및 설정
- [ ] 그라파나 도커라이즈 해서 도입
