### ISSUE TITLE
인증, 인가 관련 작성 못한 테스트 코드 작성

### ISSUE THREAD

**Issue by Dev-Yesung** [Team-PalPalHae-Dealight/Team-PalPalHae-Dealight-BE#148]
## 💻 Describe
- 이슈 설명

인증,인가 관련 작성 못한 테스트 코드가 있어서 작성하려 합니다.

## ✅ Tasks
- [ ] 인증, 인가 Controller 유닛 테스트 작성
- [x] 인증, 인가 Service 유닛 테스트 작성
- [ ] 인증, 인가 Handler 테스트 작성
