### ISSUE TITLE
상품 상세 정보 조회

### ISSUE THREAD

**Issue by hyee0715** [Team-PalPalHae-Dealight/Team-PalPalHae-Dealight-BE#16]
## 💻 Describe
- 상품 상세 정보를 조회합니다. (단건 조회)

## ✅ Tasks
- [x] 조회 서비스 로직 구현
- [ ] 조회 api 엔드포인트 연결
- [ ] 조회 테스트 코드, Rest Docs 명세 코드 작성
