### ISSUE TITLE
추가 요구사항: 닉네임 중복확인 API 구현

### ISSUE THREAD

**Issue by Dev-Yesung** [Team-PalPalHae-Dealight/Team-PalPalHae-Dealight-BE#190]
## 💻 Describe
- 이슈 설명

추가 요구사항으로 회원가입시 닉네임 중복체크 기능을 구현합니다.

## ✅ Tasks
- [x] 닉네임 중복체크 기능 구현
- [x] 테스트 코드 작성
- [x] Rest Docs에 명세 추가
