### ISSUE TITLE
무중단 배포에 필요한 EC2 추가설정, 도커 컴포즈 구성 및 컨테이너 볼륨 추가, 네트워크 구성으로 고도화

### ISSUE THREAD

**Issue by Dev-Yesung** [Team-PalPalHae-Dealight/Team-PalPalHae-Dealight-BE#192]
## 💻 Describe
EC2가 중단된 후 다시 올라갈 때 자동으로 도커 컨테이너가 실행되는 기능을 추가하려고 합니다.

또한 개발을 위해 구성했던 도커 설정을 고도화하려고 합니다.

1. 코드가 아닌 설정파일이 변경될 때, 
이미지를 다시 빌드할 필요 없이 스프링부트가 재실행될 때 
설정을 반영하도록 도커의 볼륨 기능을 추가하려 합니다.

2. 도커 컴포즈에 도커 네트워크에 관한 설정을 추가하여
컨테이너들 사이의 통신을 원활하게 만드려고 합니다.

3. 블루/그린 배포를 제외하고 인프라 관련 도커 컴포즈를 구성하려고 합니다.
이 컴포즈는 실시간 배포에서는 제외하고 EC2가 재실행되는 경우에 
컨테이너가 up이 되도록만들 예정입니다.

## ✅ Tasks
- [x] 도커 볼륨 세팅
- [x] 도커 컴포즈에 도커 네트워크 관련 설정 작성
- [x] 인프라 관련 도커 컴포즈 작성
