### ISSUE TITLE
CI/CD 파이프 라인 변경

### ISSUE THREAD

**Issue by Dev-Yesung** [Team-PalPalHae-Dealight/Team-PalPalHae-Dealight-BE#64]
## 💻 Describe
- 이슈 설명
기존 CI/CD 방식인 Github Actions -> EC2 + Docker에서
Github Actions -> S3 -> Code Deploy -> EC2 + Docker로 변경

+ Docker Compose를 이용해 Redis와 Nginx(리버스 프록시)도 사용할 예정

## ✅ Tasks
- [ ] 도커 파일 -> 도커 컴포즈로 변경
- [ ] CI/CD 파이프라인 변경에 따른 Actions script 변경
- [ ] 시크릿이 포함된 yml 파일 EC2에 업로드
- [ ] CORS 확인해보기
