### ISSUE TITLE
CI/CD 트러블 슈팅

### ISSUE THREAD

**Issue by Dev-Yesung** [Team-PalPalHae-Dealight/Team-PalPalHae-Dealight-BE#97]
## 💻 Describe
- 이슈 설명

EC2 도커 및 파일권한 관련 문제가 있어 정상적인 CI/CD가 작동하지 못하고 있습니다.
nginx포워딩과 블루그린 배포 스크립트에 문제가 생겨 정상적인 배포를 위해 수정해야 합니다.
HTTPS를 지원하지 않아 Vercel과 데이터를 주고 받는데 문제가 있습니다.
배포환경에서 카카오 로그인 페이지에 접근못하는 오류가 발생했습니다.

## ✅ Tasks
- [x] EC2 권한 관련 트러블 슈팅
- [x] Nginx 포트포워딩 설정 수정
- [x] 블루그린 배포 스크립트 수정
- [x] HTTPS 인증서 발급 후 Nginx에 적용
- [x] 카카오 로그인 페이지 접근 수정
